if(typeof protectAdminPage==='function' && !protectAdminPage()){throw new Error('Unauthorized');}
const DB_KEY='fitnessGymDB_v1', PRODUCT_KEY='fitnessGymProducts_v1';
let db=(()=>{try{return JSON.parse(localStorage.getItem(DB_KEY))||{customers:[],invoices:[],payments:[]}}catch{return {customers:[],invoices:[],payments:[]}}})();
db.customers??=[];db.invoices??=[];db.payments??=[];
const $=id=>document.getElementById(id), money=n=>`₪${Number(n||0).toLocaleString('en-US')}`, today=()=>new Date().toISOString().slice(0,10), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem(DB_KEY,JSON.stringify(db));render();}
function cid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function getCustomer(id){return db.customers.find(c=>c.id===id)}
function debt(c){return Math.max(0,Number(c.total||0)-Number(c.paid||0))}
function duplicateName(name,exclude){return db.customers.some(c=>c.id!==exclude&&c.name.trim().toLocaleLowerCase()===name.trim().toLocaleLowerCase())}
function fillSelects(){const opts=db.customers.map(c=>`<option value="${c.id}">${esc(c.name)} — ${esc(c.phone)}</option>`).join('');['debtCustomer','paymentCustomer','invoiceCustomer'].forEach(id=>{const e=$(id);if(e)e.innerHTML=opts||'<option value="">لا يوجد عملاء</option>'})}
function renderCustomers(){const q=($('customerSearch')?.value||'').trim().toLocaleLowerCase();$('customersBody').innerHTML=db.customers.filter(c=>(c.name+' '+c.phone).toLocaleLowerCase().includes(q)).map(c=>`<tr><td><b>${esc(c.name)}</b><small>${esc(c.phone)}</small></td><td>${esc(c.plan)}</td><td>${money(c.total)}</td><td>${money(c.paid)}</td><td>${money(debt(c))}</td><td>${c.start||'—'}<br>${c.end||'—'}</td><td><button class="mini danger" onclick="deleteCustomer('${c.id}')">حذف</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">لا يوجد عملاء بعد</td></tr>'}
function renderDebts(){$('debtsBody').innerHTML=db.customers.filter(debt).map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone)}</td><td>${money(c.total)}</td><td>${money(c.paid)}</td><td class="debt-cell">${money(debt(c))}</td><td><button class="mini" onclick="quickPay('${c.id}')">تسديد</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد ديون حالياً 🎉</td></tr>'}
function renderInvoices(){$('invoicesBody').innerHTML=db.invoices.slice().reverse().map(i=>{const c=getCustomer(i.customerId);return `<tr><td>${esc(i.id)}</td><td>${c?esc(c.name):'—'}</td><td>${esc(i.type)}</td><td>${money(i.amount)}</td><td>${i.date||'—'}</td><td><button class="mini danger" onclick="deleteInvoice('${i.id}')">حذف</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">لا توجد فواتير بعد</td></tr>'}
function render(){const d=db.customers.reduce((s,c)=>s+debt(c),0),p=db.customers.reduce((s,c)=>s+Number(c.paid||0),0),inv=db.invoices.reduce((s,i)=>s+Number(i.amount||0),0);$('statCustomers').textContent=db.customers.length;$('statInvoices').textContent=money(inv);$('statDebts').textContent=money(d);$('statPaid').textContent=money(p);renderCustomers();renderDebts();renderInvoices();fillSelects();if(window.renderProducts)window.renderProducts()}
$('customerForm').addEventListener('submit',e=>{e.preventDefault();const name=$('customerName').value.trim(),phone=$('customerPhone').value.trim(),total=Number($('customerTotal').value||0),paid=Number($('customerPaid').value||0);if(!name||!phone)return alert('أدخل اسم العميل ورقم الهاتف.');if(duplicateName(name))return alert('يوجد عميل آخر بنفس الاسم.');if(paid>total)return alert('المبلغ المدفوع لا يمكن أن يكون أكبر من الإجمالي.');db.customers.push({id:cid(),name,phone,plan:$('customerPlan').value,total,paid,start:$('customerStart').value,end:$('customerEnd').value});e.target.reset();save();alert('تم حفظ العميل بنجاح.')});
$('debtForm').addEventListener('submit',e=>{e.preventDefault();const c=getCustomer($('debtCustomer').value),amount=Number($('debtAmount').value||0);if(!c)return alert('اختر عميلاً.');if(amount<=0)return alert('أدخل قيمة الدين.');c.total=Number(c.total||0)+amount;db.invoices.push({id:'INV-'+Date.now(),customerId:c.id,amount,type:'دين',date:$('debtDate').value||today(),note:$('debtNote').value.trim()});e.target.reset();save();alert('تمت إضافة الدين.')});
$('paymentForm').addEventListener('submit',e=>{e.preventDefault();const c=getCustomer($('paymentCustomer').value),amount=Number($('paymentAmount').value||0);if(!c)return alert('اختر عميلاً.');if(amount<=0||amount>debt(c))return alert('قيمة الدفعة غير صحيحة.');c.paid=Number(c.paid||0)+amount;db.payments.push({id:cid(),customerId:c.id,amount,date:today(),note:$('paymentNote').value.trim()});e.target.reset();save();alert('تم تسجيل الدفعة.')});
$('invoiceForm').addEventListener('submit',e=>{e.preventDefault();const c=getCustomer($('invoiceCustomer').value),amount=Number($('invoiceAmount').value||0);if(!c)return alert('اختر عميلاً.');db.invoices.push({id:'INV-'+Date.now(),customerId:c.id,amount,type:$('invoiceType').value,date:$('invoiceDate').value||today(),note:$('invoiceNote').value.trim()});e.target.reset();$('invoiceDate').value=today();save();alert('تم إصدار الفاتورة.')});
$('customerSearch').addEventListener('input',renderCustomers);
$('invoiceDate').value=today();document.querySelectorAll('.dash-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.dash-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.dash-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('tab-'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='store'&&window.renderProducts)window.renderProducts()});
window.quickPay=id=>{document.querySelector('[data-tab="debts"]').click();$('paymentCustomer').value=id;$('paymentAmount').focus()};window.openPaymentForm=()=>document.querySelector('[data-tab="debts"]').click();window.deleteCustomer=id=>{if(confirm('حذف العميل وكل فواتيره؟')){db.customers=db.customers.filter(c=>c.id!==id);db.invoices=db.invoices.filter(i=>i.customerId!==id);db.payments=db.payments.filter(p=>p.customerId!==id);save()}};window.deleteInvoice=id=>{if(confirm('حذف الفاتورة؟')){db.invoices=db.invoices.filter(i=>i.id!==id);save()}};window.exportData=()=>{const blob=new Blob([JSON.stringify({db,products:JSON.parse(localStorage.getItem(PRODUCT_KEY)||'[]')},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fitness-gym-data.json';a.click()};render();